Public Class BE_Cliente
    Public Property codCia As String
    Public Property codCliente As String
    Public Property dsCliente As String
    Public Property dsTipoCliente As String
    Public Property dsDireccion As String
    Public Property codOperacionFacturacion As String
    Public Property dsOperacionFacturacion As String
    Public Property codMoneda As String
    Public Property dsMoneda As String
    Public Property codCondicionPago As String
    Public Property dsCondicionPago As String
    Public Property dsTipoCondicionPago As String
    Public Property nuDiasVencimiento As Integer
    Public Property codVendedor As String
    Public Property dsVendedor As String
    Public Property codZona As String
    Public Property dsZona As String
    Public Property codCobrador As String
    Public Property dsCobrador As String
    Public Property codCanalVenta As String
    Public Property dsCanalVenta As String
    Public Property codUnidadOperativa As String
    Public Property dsUnidadOperativa As String
    Public Property codListaPrecio As String
    Public Property dsListaPrecio As String
    Public Property codListaDescuento As String
    Public Property dsListaDescuento As String
    Public Property dsEstado As String
End Class
