Public Class BE_Cliente
    Public Property id As Int64
    Public Property codCia As String
    Public Property codCliente As String
    Public Property dsCliente As String
    Public Property dsTipoCliente As String
    Public Property dsTipoClasificacion As String
    Public Property dsTipoDocumento As String
    Public Property dsNroDocumento As String
    Public Property dsRuc As String
    Public Property dsApellidoPaterno As String
    Public Property dsApellidoMaterno As String
    Public Property dsNombres As String
    Public Property feNacimiento As String
    Public Property dsDireccion As String
    Public Property dsDistrito As String
    Public Property dsProvincia As String
    Public Property dsDepartamento As String
    Public Property dsPais As String
    Public Property dsFax As String
    Public Property dsTelefono1 As String
    Public Property dsTelefono2 As String
    Public Property dsCodigoPostal As String
    Public Property dsEmail1 As String
    Public Property dsEmail2 As String
    Public Property codOperacionFacturacion As String
    Public Property dsOperacionFacturacion As String
    Public Property codOperacionLogistica As String
    Public Property codMoneda As String
    Public Property dsMoneda As String
    Public Property codCondicionPago As String
    Public Property dsCondicionPago As String
    Public Property dsTipoCondicionPago As String
    Public Property nuDiasVencimiento As Integer
    Public Property codVendedor As String
    Public Property dsVendedor As String
    Public Property codZona As String
    Public Property dsZona As String
    Public Property codCobrador As String
    Public Property dsCobrador As String
    Public Property codCanalVenta As String
    Public Property dsCanalVenta As String
    Public Property codUnidadOperativa As String
    Public Property dsUnidadOperativa As String
    Public Property codListaPrecio As String
    Public Property dsListaPrecio As String
    Public Property codListaDescuento As String
    Public Property dsListaDescuento As String
    Public Property dsUsuCreacion As String
    Public Property feCreacion As Date
    Public Property dsUsuModificacion As String
    Public Property feModificacion As Date
    Public Property codUsuario As String 'Usuario Sesion
    Public Property dsEstado As String
    Public Property Accion As String
End Class
